package com.zyntasolutions.zyntapos.domain.model

import kotlinx.datetime.Instant

/**
 * A user-defined role with an explicit, admin-configurable permission set.
 *
 * Unlike the built-in [Role] enum values, custom roles can be created and deleted
 * by administrators at runtime. They are persisted in the `custom_roles` table.
 *
 * ### Relationship with built-in roles
 * - Built-in roles ([Role] enum) cannot be deleted; their default permissions
 *   can be overridden per-store via [com.zyntasolutions.zyntapos.domain.repository.RoleRepository].
 * - Custom roles are fully user-defined — the admin selects which [Permission]s to grant.
 *
 * ### User assignment
 * A [User] with a non-null `customRoleId` has their permissions resolved from the
 * [CustomRole.permissions] set instead of the built-in [Permission.rolePermissions] map.
 * The [User.role] field retains its built-in value (fallback) but is not used for
 * permission checks when [User.customRoleId] is present.
 *
 * @property id          UUID (v4) of the custom role; generated by the implementation.
 * @property name        Display name shown in the UI (e.g., "Kitchen Staff").
 * @property description Optional description explaining the role's intended scope.
 * @property permissions The set of [Permission]s granted to users assigned this role.
 * @property createdAt   UTC timestamp of creation.
 * @property updatedAt   UTC timestamp of the last modification.
 */
data class CustomRole(
    val id: String,
    val name: String,
    val description: String = "",
    val permissions: Set<Permission>,
    val createdAt: Instant,
    val updatedAt: Instant,
)
