package com.zyntasolutions.zyntapos.domain.model

/**
 * The header record of a double-entry journal entry.
 *
 * A [JournalEntry] groups one or more [JournalEntryLine] records whose debit totals
 * must equal their credit totals (balanced entry). Every financial event in ZyntaPOS
 * produces at least one [JournalEntry].
 *
 * @property id Unique identifier (UUID v4).
 * @property entryNumber Sequential, human-readable reference number.
 * @property storeId FK to the store that owns this entry.
 * @property entryDate Accounting date (ISO format: YYYY-MM-DD). Used for period allocation.
 * @property entryTime Epoch millis — used for ordering entries with the same [entryDate].
 * @property description Short narrative describing the purpose of this entry.
 * @property referenceType Category of source document that triggered this entry. See [JournalReferenceType].
 * @property referenceId FK to the source document (e.g., order ID, expense ID). Null for manual entries.
 * @property isPosted True once the entry has been reviewed and locked against further edits.
 * @property createdBy FK to the [User] who created this entry.
 * @property createdAt Epoch millis of record creation.
 * @property updatedAt Epoch millis of the last modification.
 * @property postedAt Epoch millis when [isPosted] was set to true. Null if not yet posted.
 * @property memo Extended notes visible only to accountants.
 * @property syncStatus Offline sync lifecycle state — defaults to "PENDING".
 * @property lines Detail lines (populated only when the entry is loaded with its lines).
 */
data class JournalEntry(
    val id: String,
    val entryNumber: Int,
    val storeId: String,
    val entryDate: String,
    val entryTime: Long,
    val description: String,
    val referenceType: JournalReferenceType,
    val referenceId: String? = null,
    val isPosted: Boolean = false,
    val createdBy: String,
    val createdAt: Long,
    val updatedAt: Long,
    val postedAt: Long? = null,
    val memo: String? = null,
    val syncStatus: String = "PENDING",
    val lines: List<JournalEntryLine> = emptyList(),
)

/** Category of source document that caused a [JournalEntry] to be generated. */
enum class JournalReferenceType {
    /** Generated from a completed sale order. */
    SALE,
    /** Generated from a supplier purchase invoice. */
    PURCHASE,
    /** Generated from a logged [Expense]. */
    EXPENSE,
    /** Generated from a payroll run. */
    PAYROLL,
    /** Generated from a cash-in register movement. */
    CASH_IN,
    /** Generated from a cash-out register movement. */
    CASH_OUT,
    /** Generated from a sales refund. */
    REFUND,
    /** Generated from a supplier return. */
    RETURN,
    /** Generated from a stock adjustment. */
    STOCK_ADJUST,
    /** Generated from an order-level or line-item discount. */
    DISCOUNT,
    /** Generated for a tax payment or remittance. */
    TAX_PAYMENT,
    /** Created manually by an accountant — no linked source document. */
    MANUAL,
    /** Generated by the depreciation schedule run. */
    DEPRECIATION,
    /** Generated during end-of-period closing procedures. */
    PERIOD_CLOSE,
}
