package com.zyntasolutions.zyntapos.domain.model

/**
 * A single tracking event for a stock transfer that is IN_TRANSIT (C1.4).
 *
 * Events form a chronological timeline visible in [TransitTrackerScreen].
 * Each event records *who* logged it, *when*, *where* the goods were, and
 * an optional note — providing a full audit trail from dispatch to receipt.
 *
 * @property id          Unique identifier (UUID v4).
 * @property transferId  FK to the parent [StockTransfer].
 * @property eventType   Classification of this transit update.
 * @property location    Optional human-readable location (city, address, zone).
 * @property note        Optional free-text note from the handler.
 * @property recordedBy  User ID of the staff who logged this event.
 * @property recordedAt  Epoch milliseconds when the event was recorded.
 */
data class TransitEvent(
    val id: String,
    val transferId: String,
    val eventType: EventType,
    val location: String? = null,
    val note: String? = null,
    val recordedBy: String,
    val recordedAt: Long,
) {
    /**
     * Classification of a transit tracking event.
     *
     * DISPATCHED and RECEIVED are auto-generated by the IST workflow (C1.3) and
     * shown as bookends in the timeline. CHECKPOINT, LOCATION_UPDATE, and
     * DELAY_ALERT are manually logged by staff or drivers during transit.
     */
    enum class EventType {
        /** Auto-logged when the transfer is dispatched (APPROVED → IN_TRANSIT). */
        DISPATCHED,

        /** Goods passed through an intermediate checkpoint location. */
        CHECKPOINT,

        /** Staff reported a delay — goods are still in transit. */
        DELAY_ALERT,

        /** General location update without a formal checkpoint. */
        LOCATION_UPDATE,

        /** Auto-logged when the transfer is received (IN_TRANSIT → RECEIVED). */
        RECEIVED;

        val displayName: String
            get() = when (this) {
                DISPATCHED -> "Dispatched"
                CHECKPOINT -> "Checkpoint"
                DELAY_ALERT -> "Delay Alert"
                LOCATION_UPDATE -> "Location Update"
                RECEIVED -> "Received"
            }

        val isAutoGenerated: Boolean
            get() = this == DISPATCHED || this == RECEIVED
    }
}
