package com.zyntasolutions.zyntapos.domain.repository

import com.zyntasolutions.zyntapos.core.result.Result
import com.zyntasolutions.zyntapos.domain.model.SupportTicket
import com.zyntasolutions.zyntapos.domain.model.TicketActivity
import com.zyntasolutions.zyntapos.domain.model.TicketPriority
import com.zyntasolutions.zyntapos.domain.model.TicketStatus
import kotlinx.coroutines.flow.Flow

/**
 * Contract for support ticket CRUD, assignment, and activity-log operations.
 *
 * Implementations must guarantee that every mutating call (create / update / addActivity)
 * also updates [SupportTicket.updatedAt] and enqueues a sync operation.
 */
interface SupportTicketRepository {

    /**
     * Emits all tickets, ordered by [SupportTicket.updatedAt] descending.
     * Re-emits whenever any ticket is inserted or updated.
     */
    fun getAll(): Flow<List<SupportTicket>>

    /**
     * Emits tickets filtered by [status].
     * Pass `null` to receive all tickets regardless of status.
     */
    fun getByStatus(status: TicketStatus?): Flow<List<SupportTicket>>

    /** Emits all open tickets assigned to the staff member identified by [staffId]. */
    fun getAssignedTo(staffId: String): Flow<List<SupportTicket>>

    /** Emits all tickets linked to the customer identified by [customerId]. */
    fun getByCustomer(customerId: String): Flow<List<SupportTicket>>

    /**
     * Returns a single [SupportTicket] by UUID [id], including its full [SupportTicket.activities] list.
     *
     * @return [Result.Error] if no ticket with that ID exists.
     */
    suspend fun getById(id: String): Result<SupportTicket>

    /**
     * Returns a single [SupportTicket] by its human-readable [tokenNumber]
     * (e.g. `TKT-20240307-0042`).
     *
     * @return [Result.Error] if no ticket with that token exists.
     */
    suspend fun getByToken(tokenNumber: String): Result<SupportTicket>

    /**
     * Persists a new [ticket] and enqueues a sync operation.
     * [SupportTicket.tokenNumber] must be pre-generated by the use case before calling this.
     */
    suspend fun insert(ticket: SupportTicket): Result<Unit>

    /**
     * Updates the mutable fields of [ticket] (status, priority, assignedToId,
     * resolutionNote, category, updatedAt) and enqueues a sync operation.
     */
    suspend fun update(ticket: SupportTicket): Result<Unit>

    /**
     * Appends a [TicketActivity] entry to the ticket's timeline and updates
     * [SupportTicket.updatedAt] atomically.
     */
    suspend fun addActivity(activity: TicketActivity): Result<Unit>

    /**
     * Returns the next sequential ticket number for today's date.
     * Used by the create use case to generate [SupportTicket.tokenNumber].
     *
     * Format returned: `TKT-YYYYMMDD-NNNN` (zero-padded 4-digit sequence).
     */
    suspend fun generateTokenNumber(): Result<String>

    /**
     * Full-text search across [SupportTicket.tokenNumber], [SupportTicket.subject],
     * [SupportTicket.customerName], and [SupportTicket.description].
     *
     * @param query  Search term (minimum 2 characters for FTS; shorter queries return empty).
     * @param status Optional status filter applied after text matching.
     */
    fun search(query: String, status: TicketStatus? = null): Flow<List<SupportTicket>>
}
