package com.zyntasolutions.zyntapos.domain.repository

import com.zyntasolutions.zyntapos.core.result.Result
import com.zyntasolutions.zyntapos.domain.model.QuickSwitchCandidate
import com.zyntasolutions.zyntapos.domain.model.User
import kotlinx.coroutines.flow.Flow

/**
 * Contract for user account CRUD operations within ZyntaPOS.
 *
 * This repository manages staff accounts that can log in and operate the system.
 * Authentication lifecycle (login / logout / session) remains in [AuthRepository].
 * Password hashing is delegated to the implementation layer (BCrypt on JVM,
 * Android Keystore-backed on Android).
 *
 * All mutating operations enqueue a sync event for cloud replication.
 */
interface UserRepository {

    /**
     * Emits all [User] accounts for the store, ordered by name.
     * Re-emits whenever any account is created, updated, or deactivated.
     *
     * @param storeId Scope the query to a specific store. Pass `null` for admin-level view.
     */
    fun getAll(storeId: String? = null): Flow<List<User>>

    /**
     * Returns a single [User] by [id].
     *
     * @return [Result.Error] with [com.zyntasolutions.zyntapos.core.result.ZyntaException.DatabaseException]
     *         if the user does not exist.
     */
    suspend fun getById(id: String): Result<User>

    /**
     * Creates a new user account.
     *
     * The implementation hashes [plainPassword] before storage; the raw value is
     * never persisted. Validates that [User.email] is unique across the store.
     *
     * @param user         Populated [User] model (id and createdAt generated by implementation).
     * @param plainPassword The raw password provided by the admin.
     * @return [Result.Error] with [com.zyntasolutions.zyntapos.core.result.ZyntaException.ValidationException]
     *         on duplicate email or weak password.
     */
    suspend fun create(user: User, plainPassword: String): Result<Unit>

    /**
     * Updates mutable fields of an existing user: [User.name], [User.role], [User.isActive].
     * Email and password changes require separate dedicated flows for audit-trail integrity.
     */
    suspend fun update(user: User): Result<Unit>

    /**
     * Changes the password for the user identified by [userId].
     *
     * @param userId        UUID of the target user.
     * @param newPlainPassword The new raw password to hash and store.
     */
    suspend fun updatePassword(userId: String, newPlainPassword: String): Result<Unit>

    /**
     * Deactivates (soft-deletes) the user identified by [userId].
     *
     * Deactivated users cannot log in but their historical association with orders
     * and audit events is preserved.
     */
    suspend fun deactivate(userId: String): Result<Unit>

    // ── System Admin ──────────────────────────────────────────────────────────

    /**
     * Returns the single designated system admin, or `null` if none has been set.
     *
     * There is at most one system admin per installation. The system admin is created
     * during the onboarding wizard and can be transferred via [transferSystemAdmin].
     *
     * @return [Result.Success] with the system admin [User], or `null` if no system
     *         admin is designated. [Result.Error] on database failure.
     */
    suspend fun getSystemAdmin(): Result<User?>

    /**
     * Returns whether a system admin has been designated for this installation.
     *
     * Equivalent to `getSystemAdmin().map { it != null }` but avoids loading the
     * full user record.
     *
     * @return [Result.Success]`(true)` if a system admin exists, `false` otherwise.
     *         [Result.Error] on database failure.
     */
    suspend fun adminExists(): Result<Boolean>

    /**
     * Atomically transfers system admin designation from [fromUserId] to [toUserId].
     *
     * This is the only way to change which user holds the system admin flag. The
     * operation is atomic: either both changes persist or neither does.
     *
     * The calling use case is responsible for validating business rules (both users
     * exist, [toUserId] has [com.zyntasolutions.zyntapos.domain.model.Role.ADMIN],
     * [toUserId] is active, etc.) before invoking this method.
     *
     * @param fromUserId UUID of the current system admin (loses flag).
     * @param toUserId   UUID of the user who will become the new system admin (gains flag).
     * @return [Result.Error] with [com.zyntasolutions.zyntapos.core.result.ZyntaException.DatabaseException]
     *         if either user is not found or the DB transaction fails.
     */
    suspend fun transferSystemAdmin(fromUserId: String, toUserId: String): Result<Unit>

    /**
     * Returns active users at [storeId] who have a PIN set, for the quick-switch picker.
     *
     * Only lightweight projections are returned — no sensitive hashes are exposed.
     */
    suspend fun getQuickSwitchCandidates(storeId: String): Result<List<QuickSwitchCandidate>>
}
