package com.zyntasolutions.zyntapos.domain.repository

import com.zyntasolutions.zyntapos.core.result.Result
import com.zyntasolutions.zyntapos.domain.model.User
import kotlinx.coroutines.flow.Flow

/**
 * Contract for user account CRUD operations within ZyntaPOS.
 *
 * This repository manages staff accounts that can log in and operate the system.
 * Authentication lifecycle (login / logout / session) remains in [AuthRepository].
 * Password hashing is delegated to the implementation layer (BCrypt on JVM,
 * Android Keystore-backed on Android).
 *
 * All mutating operations enqueue a sync event for cloud replication.
 */
interface UserRepository {

    /**
     * Emits all [User] accounts for the store, ordered by name.
     * Re-emits whenever any account is created, updated, or deactivated.
     *
     * @param storeId Scope the query to a specific store. Pass `null` for admin-level view.
     */
    fun getAll(storeId: String? = null): Flow<List<User>>

    /**
     * Returns a single [User] by [id].
     *
     * @return [Result.Error] with [com.zyntasolutions.zyntapos.core.result.ZentaException.DatabaseException]
     *         if the user does not exist.
     */
    suspend fun getById(id: String): Result<User>

    /**
     * Creates a new user account.
     *
     * The implementation hashes [plainPassword] before storage; the raw value is
     * never persisted. Validates that [User.email] is unique across the store.
     *
     * @param user         Populated [User] model (id and createdAt generated by implementation).
     * @param plainPassword The raw password provided by the admin.
     * @return [Result.Error] with [com.zyntasolutions.zyntapos.core.result.ZentaException.ValidationException]
     *         on duplicate email or weak password.
     */
    suspend fun create(user: User, plainPassword: String): Result<Unit>

    /**
     * Updates mutable fields of an existing user: [User.name], [User.role], [User.isActive].
     * Email and password changes require separate dedicated flows for audit-trail integrity.
     */
    suspend fun update(user: User): Result<Unit>

    /**
     * Changes the password for the user identified by [userId].
     *
     * @param userId        UUID of the target user.
     * @param newPlainPassword The new raw password to hash and store.
     */
    suspend fun updatePassword(userId: String, newPlainPassword: String): Result<Unit>

    /**
     * Deactivates (soft-deletes) the user identified by [userId].
     *
     * Deactivated users cannot log in but their historical association with orders
     * and audit events is preserved.
     */
    suspend fun deactivate(userId: String): Result<Unit>
}
