package com.zyntasolutions.zyntapos.domain.usecase.multistore

import com.zyntasolutions.zyntapos.core.result.Result
import com.zyntasolutions.zyntapos.core.result.ValidationException
import com.zyntasolutions.zyntapos.core.utils.IdGenerator
import com.zyntasolutions.zyntapos.domain.model.StockTransfer
import com.zyntasolutions.zyntapos.domain.model.TransitEvent
import com.zyntasolutions.zyntapos.domain.repository.TransitTrackingRepository
import com.zyntasolutions.zyntapos.domain.repository.WarehouseRepository
import kotlin.time.Clock

/**
 * Logs a manual transit tracking event for an IN_TRANSIT stock transfer (C1.4).
 *
 * Validates:
 * - [transferId] must not be blank
 * - [recordedBy] must not be blank
 * - [eventType] must not be an auto-generated type (DISPATCHED or RECEIVED);
 *   those are logged by the IST workflow (C1.3) directly
 * - The referenced transfer must exist and be IN_TRANSIT
 *
 * @param transitRepo     Transit tracking event data access.
 * @param warehouseRepo   Warehouse and stock transfer data access (for status check).
 */
class AddTransitEventUseCase(
    private val transitRepo: TransitTrackingRepository,
    private val warehouseRepo: WarehouseRepository,
) {
    suspend operator fun invoke(
        transferId: String,
        eventType: TransitEvent.EventType,
        recordedBy: String,
        location: String? = null,
        note: String? = null,
    ): Result<Unit> {
        if (transferId.isBlank()) {
            return Result.Error(ValidationException("Transfer ID cannot be blank"))
        }
        if (recordedBy.isBlank()) {
            return Result.Error(ValidationException("Recorder user ID cannot be blank"))
        }
        if (eventType.isAutoGenerated) {
            return Result.Error(
                ValidationException("Event type ${eventType.name} is auto-generated by the IST workflow — do not log manually")
            )
        }

        val transfer = when (val r = warehouseRepo.getTransferById(transferId)) {
            is Result.Success -> r.data
            is Result.Error -> return r
            is Result.Loading -> return Result.Loading
        }

        if (transfer.status != StockTransfer.Status.IN_TRANSIT) {
            return Result.Error(
                ValidationException(
                    "Transit events can only be added to IN_TRANSIT transfers (current status: ${transfer.status})"
                )
            )
        }

        val event = TransitEvent(
            id = IdGenerator.newId(),
            transferId = transferId,
            eventType = eventType,
            location = location?.trim()?.ifBlank { null },
            note = note?.trim()?.ifBlank { null },
            recordedBy = recordedBy,
            recordedAt = Clock.System.now().toEpochMilliseconds(),
        )

        return transitRepo.addEvent(event)
    }
}
