package com.zyntasolutions.zyntapos.data.repository

import app.cash.sqldelight.coroutines.asFlow
import app.cash.sqldelight.coroutines.mapToList
import com.zyntasolutions.zyntapos.core.result.DatabaseException
import com.zyntasolutions.zyntapos.core.result.Result
import com.zyntasolutions.zyntapos.data.local.SyncEnqueuer
import com.zyntasolutions.zyntapos.db.Accounting_periods
import com.zyntasolutions.zyntapos.db.ZyntaDatabase
import com.zyntasolutions.zyntapos.domain.model.AccountingPeriod
import com.zyntasolutions.zyntapos.domain.model.PeriodStatus
import com.zyntasolutions.zyntapos.domain.repository.AccountingPeriodRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import kotlin.time.Clock

/**
 * SQLDelight-backed implementation of [AccountingPeriodRepository].
 *
 * Accounting periods define the fiscal time boundaries for journal entry allocation.
 * State transitions are enforced in the domain use-case layer; this implementation
 * delegates directly to the SQL queries generated by `accounting_periods.sq`.
 *
 * NOTE: The `accounting_periods` table has no `store_id` column in the current schema.
 * The `storeId` parameter on interface methods is retained for future multi-store support
 * and is currently used as a filter only where a corresponding SQL query parameter exists.
 *
 * Boolean columns are stored as INTEGER (0/1 Long) — converted with `== 1L`.
 * Status is stored as TEXT — converted with `PeriodStatus.valueOf(row.status)`.
 */
class AccountingPeriodRepositoryImpl(
    private val db: ZyntaDatabase,
    private val syncEnqueuer: SyncEnqueuer,
) : AccountingPeriodRepository {

    private val q get() = db.accounting_periodsQueries

    // ── Flow observers ────────────────────────────────────────────────────────

    override fun getAll(storeId: String): Flow<List<AccountingPeriod>> =
        q.getAllPeriods()
            .asFlow()
            .mapToList(Dispatchers.IO)
            .map { rows -> rows.map(::toDomain) }

    // ── One-shot queries ──────────────────────────────────────────────────────

    override suspend fun getById(id: String): Result<AccountingPeriod?> = withContext(Dispatchers.IO) {
        runCatching {
            q.getPeriodById(id).executeAsOneOrNull()?.let(::toDomain)
        }.fold(
            onSuccess = { Result.Success(it) },
            onFailure = { t -> Result.Error(DatabaseException(t.message ?: "DB error", cause = t)) },
        )
    }

    override suspend fun getPeriodForDate(storeId: String, date: String): Result<AccountingPeriod?> =
        withContext(Dispatchers.IO) {
            runCatching {
                // getPeriodForDate returns the first period whose start_date <= date AND end_date >= date
                // (single LIMIT 1 result); no store_id filter in the current schema.
                q.getPeriodForDate(date = date).executeAsOneOrNull()?.let(::toDomain)
            }.fold(
                onSuccess = { Result.Success(it) },
                onFailure = { t -> Result.Error(DatabaseException(t.message ?: "DB error", cause = t)) },
            )
        }

    override suspend fun getOpenPeriods(storeId: String): Result<List<AccountingPeriod>> =
        withContext(Dispatchers.IO) {
            runCatching {
                q.getOpenPeriods().executeAsList().map(::toDomain)
            }.fold(
                onSuccess = { Result.Success(it) },
                onFailure = { t -> Result.Error(DatabaseException(t.message ?: "DB error", cause = t)) },
            )
        }

    // ── Mutations ─────────────────────────────────────────────────────────────

    override suspend fun create(period: AccountingPeriod): Result<Unit> = withContext(Dispatchers.IO) {
        runCatching {
            val now = Clock.System.now().toEpochMilliseconds()
            q.insertPeriod(
                id = period.id,
                period_name = period.periodName,
                start_date = period.startDate,
                end_date = period.endDate,
                status = period.status.name,
                fiscal_year_start = period.fiscalYearStart,
                is_adjustment = if (period.isAdjustment) 1L else 0L,
                created_at = now,
                updated_at = now,
            )
        }.fold(
            onSuccess = { Result.Success(Unit) },
            onFailure = { t -> Result.Error(DatabaseException(t.message ?: "Insert period failed", cause = t)) },
        )
    }

    override suspend fun closePeriod(id: String, updatedAt: Long): Result<Unit> =
        withContext(Dispatchers.IO) {
            runCatching {
                q.closePeriod(updated_at = updatedAt, id = id)
            }.fold(
                onSuccess = { Result.Success(Unit) },
                onFailure = { t -> Result.Error(DatabaseException(t.message ?: "Close period failed", cause = t)) },
            )
        }

    override suspend fun lockPeriod(id: String, lockedBy: String, lockedAt: Long): Result<Unit> =
        withContext(Dispatchers.IO) {
            runCatching {
                val now = Clock.System.now().toEpochMilliseconds()
                q.lockPeriod(
                    locked_at = lockedAt,
                    locked_by = lockedBy,
                    updated_at = now,
                    id = id,
                )
            }.fold(
                onSuccess = { Result.Success(Unit) },
                onFailure = { t -> Result.Error(DatabaseException(t.message ?: "Lock period failed", cause = t)) },
            )
        }

    override suspend fun reopenPeriod(id: String, updatedAt: Long): Result<Unit> =
        withContext(Dispatchers.IO) {
            runCatching {
                q.reopenPeriod(updated_at = updatedAt, id = id)
            }.fold(
                onSuccess = { Result.Success(Unit) },
                onFailure = { t -> Result.Error(DatabaseException(t.message ?: "Reopen period failed", cause = t)) },
            )
        }

    // ── Mapping ───────────────────────────────────────────────────────────────

    private fun toDomain(row: Accounting_periods) = AccountingPeriod(
        id = row.id,
        periodName = row.period_name,
        startDate = row.start_date,
        endDate = row.end_date,
        status = runCatching { PeriodStatus.valueOf(row.status) }.getOrDefault(PeriodStatus.OPEN),
        fiscalYearStart = row.fiscal_year_start,
        isAdjustment = row.is_adjustment == 1L,
        createdAt = row.created_at,
        updatedAt = row.updated_at,
        lockedAt = row.locked_at,
        lockedBy = row.locked_by,
    )
}
