-- ============================================================
-- V15__site_visit_token.sql
-- Adds visit_type and site_visit_token to diagnostic_sessions.
-- Phase 3 Block 6 — TODO-006 remaining.
-- ============================================================

-- visit_type: 'REMOTE' (default) or 'ON_SITE'
ALTER TABLE diagnostic_sessions
    ADD COLUMN visit_type TEXT NOT NULL DEFAULT 'REMOTE';

-- site_visit_token: short-lived opaque token for on-site kiosk auth.
-- Null for REMOTE sessions. Hashed the same way as token_hash.
-- Generated by createSiteVisitToken(); expires with the session TTL.
ALTER TABLE diagnostic_sessions
    ADD COLUMN site_visit_token_hash TEXT;

-- Index to look up sessions by the site visit token hash quickly.
CREATE INDEX idx_diag_sessions_site_visit_token
    ON diagnostic_sessions(site_visit_token_hash)
    WHERE site_visit_token_hash IS NOT NULL;
