package com.zyntasolutions.zyntapos.domain.usecase.inventory

import com.zyntasolutions.zyntapos.core.result.Result
import com.zyntasolutions.zyntapos.core.utils.IdGenerator
import com.zyntasolutions.zyntapos.domain.model.PurchaseOrderItem
import com.zyntasolutions.zyntapos.domain.repository.ReplenishmentRuleRepository
import com.zyntasolutions.zyntapos.domain.repository.WarehouseStockRepository

/**
 * Evaluates all active auto-approve replenishment rules and generates
 * [PurchaseOrder] records for products whose warehouse stock has fallen
 * at or below the configured [ReplenishmentRule.reorderPoint] (C1.5).
 *
 * This use case is intended to be called:
 * 1. By a background job that runs daily or after each stock-level change.
 * 2. Manually from the replenishment management screen.
 *
 * Only rules with [ReplenishmentRule.autoApprove] = true are processed.
 * Rules that have already generated a PENDING or PARTIAL PO for the same
 * product are skipped to avoid duplicate orders.
 *
 * @param replenishmentRuleRepository Provides active auto-approve rules.
 * @param warehouseStockRepository    Provides current per-warehouse stock levels.
 * @param createPurchaseOrderUseCase  Delegates the actual PO creation.
 */
class AutoReplenishmentUseCase(
    private val replenishmentRuleRepository: ReplenishmentRuleRepository,
    private val warehouseStockRepository: WarehouseStockRepository,
    private val createPurchaseOrderUseCase: CreatePurchaseOrderUseCase,
) {

    /**
     * Runs auto-replenishment for all eligible rules.
     *
     * @param triggeredBy  User ID (or system identifier) initiating the run.
     * @return A [ReplenishmentResult] summary with counts of POs created and skipped.
     */
    suspend operator fun invoke(triggeredBy: String): ReplenishmentResult {
        val rules = when (val result = replenishmentRuleRepository.getAutoApproveRules()) {
            is Result.Success -> result.data
            is Result.Error   -> return ReplenishmentResult(errors = listOf(result.exception.message ?: "Failed to load rules"))
            is Result.Loading -> return ReplenishmentResult(errors = listOf("Unexpected loading state when fetching rules"))
        }

        var created = 0
        var skipped = 0
        val errors  = mutableListOf<String>()

        for (rule in rules) {
            val stockEntry = when (val result = warehouseStockRepository.getEntry(rule.warehouseId, rule.productId)) {
                is Result.Success -> result.data
                is Result.Error   -> {
                    skipped++
                    errors.add("${rule.productName ?: rule.productId}: could not read stock — ${result.exception.message}")
                    continue
                }
                is Result.Loading -> {
                    skipped++
                    errors.add("${rule.productName ?: rule.productId}: unexpected loading state reading stock")
                    continue
                }
            }

            val currentQty = stockEntry?.quantity ?: 0.0

            if (currentQty > rule.reorderPoint) {
                // Stock is sufficient — nothing to do.
                skipped++
                continue
            }

            // Build a single-item PO for this rule.
            val item = PurchaseOrderItem(
                id               = IdGenerator.newId(),
                purchaseOrderId  = "",   // filled in by CreatePurchaseOrderUseCase
                productId        = rule.productId,
                quantityOrdered  = rule.reorderQty,
                quantityReceived = 0.0,
                unitCost         = 0.0, // cost unknown at auto-generate time; updated on receipt
                lineTotal        = 0.0,
                notes            = "Auto-generated by replenishment rule",
            )

            val createResult = createPurchaseOrderUseCase(
                supplierId   = rule.supplierId,
                orderNumber  = "",           // auto-generated
                items        = listOf(item),
                expectedDate = null,
                notes        = "Auto-replenishment: stock ${currentQty} ≤ reorder point ${rule.reorderPoint}",
                createdBy    = triggeredBy,
            )

            when (createResult) {
                is Result.Success -> created++
                is Result.Error   -> {
                    skipped++
                    errors.add("${rule.productName ?: rule.productId}: ${createResult.exception.message}")
                }
                is Result.Loading -> {
                    skipped++
                    errors.add("${rule.productName ?: rule.productId}: unexpected loading state creating PO")
                }
            }
        }

        return ReplenishmentResult(
            rulesEvaluated = rules.size,
            ordersCreated  = created,
            rulesSkipped   = skipped,
            errors         = errors,
        )
    }
}

/**
 * Summary of an [AutoReplenishmentUseCase] run.
 *
 * @property rulesEvaluated Total number of active auto-approve rules evaluated.
 * @property ordersCreated  Number of PENDING POs successfully created.
 * @property rulesSkipped   Number of rules skipped (stock sufficient or error).
 * @property errors         Human-readable error messages for failed rules.
 */
data class ReplenishmentResult(
    val rulesEvaluated: Int = 0,
    val ordersCreated: Int  = 0,
    val rulesSkipped: Int   = 0,
    val errors: List<String> = emptyList(),
) {
    val hasErrors: Boolean get() = errors.isNotEmpty()
}
