package com.zyntasolutions.zyntapos.domain.usecase.settings

import com.zyntasolutions.zyntapos.hal.printer.EscPosReceiptBuilder
import com.zyntasolutions.zyntapos.hal.printer.PaperWidth
import com.zyntasolutions.zyntapos.hal.printer.PrinterConfig
import com.zyntasolutions.zyntapos.hal.printer.PrinterManager

/**
 * Sends a built-in ESC/POS self-test page to the configured [PrinterManager].
 *
 * The test page verifies:
 * - Paper width alignment (ruler line)
 * - Character encoding
 * - Print density
 *
 * The test page is generated by [EscPosReceiptBuilder.buildTestPage] which is
 * already implemented in the HAL layer; this use case is a thin orchestration
 * wrapper that wires the settings-configured [PaperWidth] into a [PrinterConfig]
 * and hands the byte array to [PrinterManager].
 *
 * @param printerManager HAL gateway for thermal printer I/O.
 */
class PrintTestPageUseCase(
    private val printerManager: PrinterManager,
) {
    /**
     * Builds and transmits a test page.
     *
     * @param paperWidth Active paper width — drives character column count.
     * @return [Result.success] when the job is queued or delivered;
     *         [Result.failure] with the underlying [Throwable] on transport error.
     */
    suspend operator fun invoke(
        paperWidth: PaperWidth = PaperWidth.MM_80,
    ): Result<Unit> {
        val config = PrinterConfig(paperWidth = paperWidth)
        val bytes = EscPosReceiptBuilder(config).buildTestPage()
        return printerManager.print(bytes)
    }
}
