/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TicketsIndexRouteImport } from './routes/tickets/index'
import { Route as SyncIndexRouteImport } from './routes/sync/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as MasterProductsIndexRouteImport } from './routes/master-products/index'
import { Route as LicensesIndexRouteImport } from './routes/licenses/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as DiagnosticIndexRouteImport } from './routes/diagnostic/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets/$ticketId'
import { Route as TicketStatusTokenRouteImport } from './routes/ticket-status/$token'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsMfaRouteImport } from './routes/settings/mfa'
import { Route as SettingsExchangeRatesRouteImport } from './routes/settings/exchange-rates'
import { Route as SettingsEmailRouteImport } from './routes/settings/email'
import { Route as MasterProductsMasterProductIdRouteImport } from './routes/master-products/$masterProductId'
import { Route as LicensesLicenseKeyRouteImport } from './routes/licenses/$licenseKey'
import { Route as HealthStoreIdRouteImport } from './routes/health/$storeId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIndexRoute = SyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProductsIndexRoute = MasterProductsIndexRouteImport.update({
  id: '/master-products/',
  path: '/master-products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesIndexRoute = LicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticIndexRoute = DiagnosticIndexRouteImport.update({
  id: '/diagnostic/',
  path: '/diagnostic/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketStatusTokenRoute = TicketStatusTokenRouteImport.update({
  id: '/ticket-status/$token',
  path: '/ticket-status/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMfaRoute = SettingsMfaRouteImport.update({
  id: '/settings/mfa',
  path: '/settings/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsExchangeRatesRoute = SettingsExchangeRatesRouteImport.update({
  id: '/settings/exchange-rates',
  path: '/settings/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEmailRoute = SettingsEmailRouteImport.update({
  id: '/settings/email',
  path: '/settings/email',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterProductsMasterProductIdRoute =
  MasterProductsMasterProductIdRouteImport.update({
    id: '/master-products/$masterProductId',
    path: '/master-products/$masterProductId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LicensesLicenseKeyRoute = LicensesLicenseKeyRouteImport.update({
  id: '/licenses/$licenseKey',
  path: '/licenses/$licenseKey',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthStoreIdRoute = HealthStoreIdRouteImport.update({
  id: '/health/$storeId',
  path: '/health/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/health/$storeId': typeof HealthStoreIdRoute
  '/licenses/$licenseKey': typeof LicensesLicenseKeyRoute
  '/master-products/$masterProductId': typeof MasterProductsMasterProductIdRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/exchange-rates': typeof SettingsExchangeRatesRoute
  '/settings/mfa': typeof SettingsMfaRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/ticket-status/$token': typeof TicketStatusTokenRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/health/': typeof HealthIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/licenses/': typeof LicensesIndexRoute
  '/master-products/': typeof MasterProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/sync/': typeof SyncIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/health/$storeId': typeof HealthStoreIdRoute
  '/licenses/$licenseKey': typeof LicensesLicenseKeyRoute
  '/master-products/$masterProductId': typeof MasterProductsMasterProductIdRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/exchange-rates': typeof SettingsExchangeRatesRoute
  '/settings/mfa': typeof SettingsMfaRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/ticket-status/$token': typeof TicketStatusTokenRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/audit': typeof AuditIndexRoute
  '/config': typeof ConfigIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/diagnostic': typeof DiagnosticIndexRoute
  '/health': typeof HealthIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/licenses': typeof LicensesIndexRoute
  '/master-products': typeof MasterProductsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/security': typeof SecurityIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/stores': typeof StoresIndexRoute
  '/sync': typeof SyncIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/health/$storeId': typeof HealthStoreIdRoute
  '/licenses/$licenseKey': typeof LicensesLicenseKeyRoute
  '/master-products/$masterProductId': typeof MasterProductsMasterProductIdRoute
  '/settings/email': typeof SettingsEmailRoute
  '/settings/exchange-rates': typeof SettingsExchangeRatesRoute
  '/settings/mfa': typeof SettingsMfaRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/ticket-status/$token': typeof TicketStatusTokenRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/diagnostic/': typeof DiagnosticIndexRoute
  '/health/': typeof HealthIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/licenses/': typeof LicensesIndexRoute
  '/master-products/': typeof MasterProductsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/sync/': typeof SyncIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/health/$storeId'
    | '/licenses/$licenseKey'
    | '/master-products/$masterProductId'
    | '/settings/email'
    | '/settings/exchange-rates'
    | '/settings/mfa'
    | '/settings/profile'
    | '/stores/$storeId'
    | '/ticket-status/$token'
    | '/tickets/$ticketId'
    | '/alerts/'
    | '/audit/'
    | '/config/'
    | '/customers/'
    | '/diagnostic/'
    | '/health/'
    | '/inventory/'
    | '/licenses/'
    | '/master-products/'
    | '/reports/'
    | '/security/'
    | '/settings/'
    | '/setup/'
    | '/stores/'
    | '/sync/'
    | '/tickets/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/health/$storeId'
    | '/licenses/$licenseKey'
    | '/master-products/$masterProductId'
    | '/settings/email'
    | '/settings/exchange-rates'
    | '/settings/mfa'
    | '/settings/profile'
    | '/stores/$storeId'
    | '/ticket-status/$token'
    | '/tickets/$ticketId'
    | '/alerts'
    | '/audit'
    | '/config'
    | '/customers'
    | '/diagnostic'
    | '/health'
    | '/inventory'
    | '/licenses'
    | '/master-products'
    | '/reports'
    | '/security'
    | '/settings'
    | '/setup'
    | '/stores'
    | '/sync'
    | '/tickets'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/health/$storeId'
    | '/licenses/$licenseKey'
    | '/master-products/$masterProductId'
    | '/settings/email'
    | '/settings/exchange-rates'
    | '/settings/mfa'
    | '/settings/profile'
    | '/stores/$storeId'
    | '/ticket-status/$token'
    | '/tickets/$ticketId'
    | '/alerts/'
    | '/audit/'
    | '/config/'
    | '/customers/'
    | '/diagnostic/'
    | '/health/'
    | '/inventory/'
    | '/licenses/'
    | '/master-products/'
    | '/reports/'
    | '/security/'
    | '/settings/'
    | '/setup/'
    | '/stores/'
    | '/sync/'
    | '/tickets/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  HealthStoreIdRoute: typeof HealthStoreIdRoute
  LicensesLicenseKeyRoute: typeof LicensesLicenseKeyRoute
  MasterProductsMasterProductIdRoute: typeof MasterProductsMasterProductIdRoute
  SettingsEmailRoute: typeof SettingsEmailRoute
  SettingsExchangeRatesRoute: typeof SettingsExchangeRatesRoute
  SettingsMfaRoute: typeof SettingsMfaRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  TicketStatusTokenRoute: typeof TicketStatusTokenRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  DiagnosticIndexRoute: typeof DiagnosticIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  LicensesIndexRoute: typeof LicensesIndexRoute
  MasterProductsIndexRoute: typeof MasterProductsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  SyncIndexRoute: typeof SyncIndexRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/': {
      id: '/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof SyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-products/': {
      id: '/master-products/'
      path: '/master-products'
      fullPath: '/master-products/'
      preLoaderRoute: typeof MasterProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/': {
      id: '/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof LicensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic/': {
      id: '/diagnostic/'
      path: '/diagnostic'
      fullPath: '/diagnostic/'
      preLoaderRoute: typeof DiagnosticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-status/$token': {
      id: '/ticket-status/$token'
      path: '/ticket-status/$token'
      fullPath: '/ticket-status/$token'
      preLoaderRoute: typeof TicketStatusTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mfa': {
      id: '/settings/mfa'
      path: '/settings/mfa'
      fullPath: '/settings/mfa'
      preLoaderRoute: typeof SettingsMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/exchange-rates': {
      id: '/settings/exchange-rates'
      path: '/settings/exchange-rates'
      fullPath: '/settings/exchange-rates'
      preLoaderRoute: typeof SettingsExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/email': {
      id: '/settings/email'
      path: '/settings/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof SettingsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-products/$masterProductId': {
      id: '/master-products/$masterProductId'
      path: '/master-products/$masterProductId'
      fullPath: '/master-products/$masterProductId'
      preLoaderRoute: typeof MasterProductsMasterProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/$licenseKey': {
      id: '/licenses/$licenseKey'
      path: '/licenses/$licenseKey'
      fullPath: '/licenses/$licenseKey'
      preLoaderRoute: typeof LicensesLicenseKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$storeId': {
      id: '/health/$storeId'
      path: '/health/$storeId'
      fullPath: '/health/$storeId'
      preLoaderRoute: typeof HealthStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  HealthStoreIdRoute: HealthStoreIdRoute,
  LicensesLicenseKeyRoute: LicensesLicenseKeyRoute,
  MasterProductsMasterProductIdRoute: MasterProductsMasterProductIdRoute,
  SettingsEmailRoute: SettingsEmailRoute,
  SettingsExchangeRatesRoute: SettingsExchangeRatesRoute,
  SettingsMfaRoute: SettingsMfaRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  TicketStatusTokenRoute: TicketStatusTokenRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DiagnosticIndexRoute: DiagnosticIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  LicensesIndexRoute: LicensesIndexRoute,
  MasterProductsIndexRoute: MasterProductsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  SyncIndexRoute: SyncIndexRoute,
  TicketsIndexRoute: TicketsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
