/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as SyncIndexRouteImport } from './routes/sync/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as LicensesIndexRouteImport } from './routes/licenses/index'
import { Route as HealthIndexRouteImport } from './routes/health/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as LicensesLicenseKeyRouteImport } from './routes/licenses/$licenseKey'
import { Route as HealthStoreIdRouteImport } from './routes/health/$storeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncIndexRoute = SyncIndexRouteImport.update({
  id: '/sync/',
  path: '/sync/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesIndexRoute = LicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesLicenseKeyRoute = LicensesLicenseKeyRouteImport.update({
  id: '/licenses/$licenseKey',
  path: '/licenses/$licenseKey',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthStoreIdRoute = HealthStoreIdRouteImport.update({
  id: '/health/$storeId',
  path: '/health/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof IndexRoute
  '/health/$storeId': typeof HealthStoreIdRoute
  '/licenses/$licenseKey': typeof LicensesLicenseKeyRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/health/': typeof HealthIndexRoute
  '/licenses/': typeof LicensesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/sync/': typeof SyncIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof IndexRoute
  '/health/$storeId': typeof HealthStoreIdRoute
  '/licenses/$licenseKey': typeof LicensesLicenseKeyRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/audit': typeof AuditIndexRoute
  '/config': typeof ConfigIndexRoute
  '/health': typeof HealthIndexRoute
  '/licenses': typeof LicensesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stores': typeof StoresIndexRoute
  '/sync': typeof SyncIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/': typeof IndexRoute
  '/health/$storeId': typeof HealthStoreIdRoute
  '/licenses/$licenseKey': typeof LicensesLicenseKeyRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/health/': typeof HealthIndexRoute
  '/licenses/': typeof LicensesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/sync/': typeof SyncIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/health/$storeId'
    | '/licenses/$licenseKey'
    | '/stores/$storeId'
    | '/alerts/'
    | '/audit/'
    | '/config/'
    | '/health/'
    | '/licenses/'
    | '/reports/'
    | '/settings/'
    | '/stores/'
    | '/sync/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/health/$storeId'
    | '/licenses/$licenseKey'
    | '/stores/$storeId'
    | '/alerts'
    | '/audit'
    | '/config'
    | '/health'
    | '/licenses'
    | '/reports'
    | '/settings'
    | '/stores'
    | '/sync'
    | '/users'
  id:
    | '__root__'
    | '/login'
    | '/'
    | '/health/$storeId'
    | '/licenses/$licenseKey'
    | '/stores/$storeId'
    | '/alerts/'
    | '/audit/'
    | '/config/'
    | '/health/'
    | '/licenses/'
    | '/reports/'
    | '/settings/'
    | '/stores/'
    | '/sync/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  IndexRoute: typeof IndexRoute
  HealthStoreIdRoute: typeof HealthStoreIdRoute
  LicensesLicenseKeyRoute: typeof LicensesLicenseKeyRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  HealthIndexRoute: typeof HealthIndexRoute
  LicensesIndexRoute: typeof LicensesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  SyncIndexRoute: typeof SyncIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync/': {
      id: '/sync/'
      path: '/sync'
      fullPath: '/sync/'
      preLoaderRoute: typeof SyncIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/': {
      id: '/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof LicensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/$licenseKey': {
      id: '/licenses/$licenseKey'
      path: '/licenses/$licenseKey'
      fullPath: '/licenses/$licenseKey'
      preLoaderRoute: typeof LicensesLicenseKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$storeId': {
      id: '/health/$storeId'
      path: '/health/$storeId'
      fullPath: '/health/$storeId'
      preLoaderRoute: typeof HealthStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  IndexRoute: IndexRoute,
  HealthStoreIdRoute: HealthStoreIdRoute,
  LicensesLicenseKeyRoute: LicensesLicenseKeyRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  HealthIndexRoute: HealthIndexRoute,
  LicensesIndexRoute: LicensesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  SyncIndexRoute: SyncIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
